// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-data.proto

package com.github.stepancheg.protobuftojson.test;

public final class TestData {
  private TestData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CitizenOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 age = 2;
    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();
  }
  /**
   * Protobuf type {@code com.github.stepancheg.protobuftojson.test.Citizen}
   */
  public static final class Citizen extends
      com.google.protobuf.GeneratedMessage
      implements CitizenOrBuilder {
    // Use Citizen.newBuilder() to construct.
    private Citizen(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Citizen(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Citizen defaultInstance;
    public static Citizen getDefaultInstance() {
      return defaultInstance;
    }

    public Citizen getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Citizen(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_Citizen_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_Citizen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.stepancheg.protobuftojson.test.TestData.Citizen.class, com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder.class);
    }

    public static com.google.protobuf.Parser<Citizen> PARSER =
        new com.google.protobuf.AbstractParser<Citizen>() {
      public Citizen parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Citizen(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Citizen> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 age = 2;
    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    private void initFields() {
      name_ = "";
      age_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, age_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.Citizen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.stepancheg.protobuftojson.test.TestData.Citizen prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.stepancheg.protobuftojson.test.Citizen}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_Citizen_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_Citizen_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.stepancheg.protobuftojson.test.TestData.Citizen.class, com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder.class);
      }

      // Construct using com.github.stepancheg.protobuftojson.test.TestData.Citizen.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_Citizen_descriptor;
      }

      public com.github.stepancheg.protobuftojson.test.TestData.Citizen getDefaultInstanceForType() {
        return com.github.stepancheg.protobuftojson.test.TestData.Citizen.getDefaultInstance();
      }

      public com.github.stepancheg.protobuftojson.test.TestData.Citizen build() {
        com.github.stepancheg.protobuftojson.test.TestData.Citizen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.stepancheg.protobuftojson.test.TestData.Citizen buildPartial() {
        com.github.stepancheg.protobuftojson.test.TestData.Citizen result = new com.github.stepancheg.protobuftojson.test.TestData.Citizen(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.age_ = age_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.stepancheg.protobuftojson.test.TestData.Citizen) {
          return mergeFrom((com.github.stepancheg.protobuftojson.test.TestData.Citizen)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.stepancheg.protobuftojson.test.TestData.Citizen other) {
        if (other == com.github.stepancheg.protobuftojson.test.TestData.Citizen.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.stepancheg.protobuftojson.test.TestData.Citizen parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.stepancheg.protobuftojson.test.TestData.Citizen) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 age = 2;
      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.stepancheg.protobuftojson.test.Citizen)
    }

    static {
      defaultInstance = new Citizen(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.github.stepancheg.protobuftojson.test.Citizen)
  }

  public interface CityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    java.util.List<com.github.stepancheg.protobuftojson.test.TestData.Citizen> 
        getCitizensList();
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    com.github.stepancheg.protobuftojson.test.TestData.Citizen getCitizens(int index);
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    int getCitizensCount();
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    java.util.List<? extends com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder> 
        getCitizensOrBuilderList();
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder getCitizensOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.github.stepancheg.protobuftojson.test.City}
   */
  public static final class City extends
      com.google.protobuf.GeneratedMessage
      implements CityOrBuilder {
    // Use City.newBuilder() to construct.
    private City(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private City(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final City defaultInstance;
    public static City getDefaultInstance() {
      return defaultInstance;
    }

    public City getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private City(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                citizens_ = new java.util.ArrayList<com.github.stepancheg.protobuftojson.test.TestData.Citizen>();
                mutable_bitField0_ |= 0x00000002;
              }
              citizens_.add(input.readMessage(com.github.stepancheg.protobuftojson.test.TestData.Citizen.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          citizens_ = java.util.Collections.unmodifiableList(citizens_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_City_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_City_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.stepancheg.protobuftojson.test.TestData.City.class, com.github.stepancheg.protobuftojson.test.TestData.City.Builder.class);
    }

    public static com.google.protobuf.Parser<City> PARSER =
        new com.google.protobuf.AbstractParser<City>() {
      public City parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new City(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<City> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;
    public static final int CITIZENS_FIELD_NUMBER = 2;
    private java.util.List<com.github.stepancheg.protobuftojson.test.TestData.Citizen> citizens_;
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    public java.util.List<com.github.stepancheg.protobuftojson.test.TestData.Citizen> getCitizensList() {
      return citizens_;
    }
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    public java.util.List<? extends com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder> 
        getCitizensOrBuilderList() {
      return citizens_;
    }
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    public int getCitizensCount() {
      return citizens_.size();
    }
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    public com.github.stepancheg.protobuftojson.test.TestData.Citizen getCitizens(int index) {
      return citizens_.get(index);
    }
    /**
     * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
     */
    public com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder getCitizensOrBuilder(
        int index) {
      return citizens_.get(index);
    }

    private void initFields() {
      name_ = "";
      citizens_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < citizens_.size(); i++) {
        output.writeMessage(2, citizens_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < citizens_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, citizens_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.protobuftojson.test.TestData.City parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.stepancheg.protobuftojson.test.TestData.City prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.stepancheg.protobuftojson.test.City}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.stepancheg.protobuftojson.test.TestData.CityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_City_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_City_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.stepancheg.protobuftojson.test.TestData.City.class, com.github.stepancheg.protobuftojson.test.TestData.City.Builder.class);
      }

      // Construct using com.github.stepancheg.protobuftojson.test.TestData.City.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCitizensFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (citizensBuilder_ == null) {
          citizens_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          citizensBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.stepancheg.protobuftojson.test.TestData.internal_static_com_github_stepancheg_protobuftojson_test_City_descriptor;
      }

      public com.github.stepancheg.protobuftojson.test.TestData.City getDefaultInstanceForType() {
        return com.github.stepancheg.protobuftojson.test.TestData.City.getDefaultInstance();
      }

      public com.github.stepancheg.protobuftojson.test.TestData.City build() {
        com.github.stepancheg.protobuftojson.test.TestData.City result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.stepancheg.protobuftojson.test.TestData.City buildPartial() {
        com.github.stepancheg.protobuftojson.test.TestData.City result = new com.github.stepancheg.protobuftojson.test.TestData.City(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (citizensBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            citizens_ = java.util.Collections.unmodifiableList(citizens_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.citizens_ = citizens_;
        } else {
          result.citizens_ = citizensBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.stepancheg.protobuftojson.test.TestData.City) {
          return mergeFrom((com.github.stepancheg.protobuftojson.test.TestData.City)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.stepancheg.protobuftojson.test.TestData.City other) {
        if (other == com.github.stepancheg.protobuftojson.test.TestData.City.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (citizensBuilder_ == null) {
          if (!other.citizens_.isEmpty()) {
            if (citizens_.isEmpty()) {
              citizens_ = other.citizens_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCitizensIsMutable();
              citizens_.addAll(other.citizens_);
            }
            onChanged();
          }
        } else {
          if (!other.citizens_.isEmpty()) {
            if (citizensBuilder_.isEmpty()) {
              citizensBuilder_.dispose();
              citizensBuilder_ = null;
              citizens_ = other.citizens_;
              bitField0_ = (bitField0_ & ~0x00000002);
              citizensBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCitizensFieldBuilder() : null;
            } else {
              citizensBuilder_.addAllMessages(other.citizens_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.stepancheg.protobuftojson.test.TestData.City parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.stepancheg.protobuftojson.test.TestData.City) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;
      private java.util.List<com.github.stepancheg.protobuftojson.test.TestData.Citizen> citizens_ =
        java.util.Collections.emptyList();
      private void ensureCitizensIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          citizens_ = new java.util.ArrayList<com.github.stepancheg.protobuftojson.test.TestData.Citizen>(citizens_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.github.stepancheg.protobuftojson.test.TestData.Citizen, com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder, com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder> citizensBuilder_;

      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public java.util.List<com.github.stepancheg.protobuftojson.test.TestData.Citizen> getCitizensList() {
        if (citizensBuilder_ == null) {
          return java.util.Collections.unmodifiableList(citizens_);
        } else {
          return citizensBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public int getCitizensCount() {
        if (citizensBuilder_ == null) {
          return citizens_.size();
        } else {
          return citizensBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public com.github.stepancheg.protobuftojson.test.TestData.Citizen getCitizens(int index) {
        if (citizensBuilder_ == null) {
          return citizens_.get(index);
        } else {
          return citizensBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder setCitizens(
          int index, com.github.stepancheg.protobuftojson.test.TestData.Citizen value) {
        if (citizensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCitizensIsMutable();
          citizens_.set(index, value);
          onChanged();
        } else {
          citizensBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder setCitizens(
          int index, com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder builderForValue) {
        if (citizensBuilder_ == null) {
          ensureCitizensIsMutable();
          citizens_.set(index, builderForValue.build());
          onChanged();
        } else {
          citizensBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder addCitizens(com.github.stepancheg.protobuftojson.test.TestData.Citizen value) {
        if (citizensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCitizensIsMutable();
          citizens_.add(value);
          onChanged();
        } else {
          citizensBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder addCitizens(
          int index, com.github.stepancheg.protobuftojson.test.TestData.Citizen value) {
        if (citizensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCitizensIsMutable();
          citizens_.add(index, value);
          onChanged();
        } else {
          citizensBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder addCitizens(
          com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder builderForValue) {
        if (citizensBuilder_ == null) {
          ensureCitizensIsMutable();
          citizens_.add(builderForValue.build());
          onChanged();
        } else {
          citizensBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder addCitizens(
          int index, com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder builderForValue) {
        if (citizensBuilder_ == null) {
          ensureCitizensIsMutable();
          citizens_.add(index, builderForValue.build());
          onChanged();
        } else {
          citizensBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder addAllCitizens(
          java.lang.Iterable<? extends com.github.stepancheg.protobuftojson.test.TestData.Citizen> values) {
        if (citizensBuilder_ == null) {
          ensureCitizensIsMutable();
          super.addAll(values, citizens_);
          onChanged();
        } else {
          citizensBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder clearCitizens() {
        if (citizensBuilder_ == null) {
          citizens_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          citizensBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public Builder removeCitizens(int index) {
        if (citizensBuilder_ == null) {
          ensureCitizensIsMutable();
          citizens_.remove(index);
          onChanged();
        } else {
          citizensBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder getCitizensBuilder(
          int index) {
        return getCitizensFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder getCitizensOrBuilder(
          int index) {
        if (citizensBuilder_ == null) {
          return citizens_.get(index);  } else {
          return citizensBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public java.util.List<? extends com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder> 
           getCitizensOrBuilderList() {
        if (citizensBuilder_ != null) {
          return citizensBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(citizens_);
        }
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder addCitizensBuilder() {
        return getCitizensFieldBuilder().addBuilder(
            com.github.stepancheg.protobuftojson.test.TestData.Citizen.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder addCitizensBuilder(
          int index) {
        return getCitizensFieldBuilder().addBuilder(
            index, com.github.stepancheg.protobuftojson.test.TestData.Citizen.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.stepancheg.protobuftojson.test.Citizen citizens = 2;</code>
       */
      public java.util.List<com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder> 
           getCitizensBuilderList() {
        return getCitizensFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.github.stepancheg.protobuftojson.test.TestData.Citizen, com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder, com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder> 
          getCitizensFieldBuilder() {
        if (citizensBuilder_ == null) {
          citizensBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.github.stepancheg.protobuftojson.test.TestData.Citizen, com.github.stepancheg.protobuftojson.test.TestData.Citizen.Builder, com.github.stepancheg.protobuftojson.test.TestData.CitizenOrBuilder>(
                  citizens_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          citizens_ = null;
        }
        return citizensBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.github.stepancheg.protobuftojson.test.City)
    }

    static {
      defaultInstance = new City(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.github.stepancheg.protobuftojson.test.City)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_stepancheg_protobuftojson_test_Citizen_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_stepancheg_protobuftojson_test_Citizen_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_stepancheg_protobuftojson_test_City_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_stepancheg_protobuftojson_test_City_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017test-data.proto\022)com.github.stepancheg" +
      ".protobuftojson.test\"$\n\007Citizen\022\014\n\004name\030" +
      "\001 \001(\t\022\013\n\003age\030\002 \001(\005\"Z\n\004City\022\014\n\004name\030\001 \002(\t" +
      "\022D\n\010citizens\030\002 \003(\01322.com.github.stepanch" +
      "eg.protobuftojson.test.Citizen"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_github_stepancheg_protobuftojson_test_Citizen_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_github_stepancheg_protobuftojson_test_Citizen_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_stepancheg_protobuftojson_test_Citizen_descriptor,
              new java.lang.String[] { "Name", "Age", });
          internal_static_com_github_stepancheg_protobuftojson_test_City_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_github_stepancheg_protobuftojson_test_City_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_stepancheg_protobuftojson_test_City_descriptor,
              new java.lang.String[] { "Name", "Citizens", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
